name: "Initialize Java Maven"
description: "Checkout and setup Java and maven cache(based on pom.xml)"
inputs:
  java-version:
    description: "Java version to Initialize repo"
    required: false
    default: "17"
  distribution:
    description: "Whether to cache dependencies or not."
    required: false
    default: "adopt"
  maven-id:
    description: 'Repo ID'
    required: false
    default: 'my-maven-repo'
  maven-url:
    description: 'URL of Maven Repo to Deploy'
    required: true
  maven-username:
    description: 'Maven Username'
    required: true
  maven-password:
    description: 'Maven Password'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Configure Maven To Deploy
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        repositories: '[{ "id": "${{ inputs.maven-id }}", "url": "${{ inputs.maven-url }}" }]'
        plugin_repositories: '[{ "id": "${{ inputs.maven-id }}-plugins", "url": "${{ inputs.maven-url }}" }]'
        servers: '[{ "id": "${{ inputs.maven-id }}", "username": "${{ inputs.maven-username }}", "password": "${{ inputs.maven-password }}" },{ "id": "${{ inputs.maven-id }}-plugins", "username": "${{ inputs.maven-username }}", "password": "${{ inputs.maven-password }}" }]'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mvn compile
      shell: bash