name: "Initialize Java Maven"
description: "Checkout and setup Java and maven cache(based on pom.xml)"
inputs:
  java-version:
    description: "Java version to Initialize repo"
    required: false
    default: "17"
  distribution:
    description: "Whether to cache dependencies or not."
    required: false
    default: "adopt"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Cache local Maven repository
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mvn compile
      shell: bash